# Compiler
CXX = g++

# Compiler flags
CXXFLAGS = -Wall -Wextra -std=c++17 -O2 -MMD

# Qt package (override with QT_PKG=Qt6Widgets if desired)
QT_PKG ?= Qt5Widgets
QT_CFLAGS := $(shell pkg-config --cflags $(QT_PKG))
QT_LIBS := $(shell pkg-config --libs $(QT_PKG))

ifeq ($(QT_CFLAGS),)
$(error pkg-config could not find $(QT_PKG). Install Qt development files or set QT_PKG accordingly)
endif

# Linker flags
LDFLAGS = $(QT_LIBS)

# Directories
BUILD_DIR = build
BIN_DIR = bin

# Target executable
TARGET = $(BIN_DIR)/main

# Test target executable
TEST_TARGET = $(BIN_DIR)/test

# Source files
SRCS = main.cpp utils.cpp conversion.cpp gui.cpp

# Object files (placed in build directory)
OBJS = $(SRCS:%.cpp=$(BUILD_DIR)/%.o)

# Dependencies generated by gcc
DEPS = $(SRCS:%.cpp=$(BUILD_DIR)/%.d)

ifeq ($(OS),Windows_NT)
	TARGET := $(TARGET).exe
	TEST_TARGET := $(TEST_TARGET).exe

	# CMD
	RM = del /f /q
	RMDIR = del /f /q /s
endif

# Default target
all: $(TARGET)

# Create directories if they don't exist
$(BUILD_DIR) $(BIN_DIR):
	mkdir -p $@

# Link object files to create executable
$(TARGET): $(OBJS) | $(BIN_DIR)
	$(CXX) $(CXXFLAGS) -o $(TARGET) $(OBJS) $(LDFLAGS)

# Compile source files to object files in build directory
$(BUILD_DIR)/%.o: %.cpp | $(BUILD_DIR)
	$(CXX) $(CXXFLAGS) $(QT_CFLAGS) -c $< -o $@

# Run the program
run: $(TARGET)
	./$(TARGET)

# Clean generated files and directories
clean:
	$(RM) $(DEPS)
	$(RMDIR) $(BUILD_DIR) $(BIN_DIR)

# Tests
$(TEST_TARGET): $(BUILD_DIR)/utils.o $(BUILD_DIR)/conversion.o $(BUILD_DIR)/test.o
	$(CXX) -o $@ $^

$(BUILD_DIR)/test.o: test.cpp
	$(CXX) $(CFLAGS) -c -o $@ $^

runtest: $(TEST_TARGET)
	./$(TEST_TARGET)

# Phony targets
.PHONY: all run clean runtest

# import auto dependencies generated by gcc
-include $(DEPS)
